# Generated by Django 5.2.7 on 2025-11-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesapp',
            name='updated_at',
        ),
    ]
